apiVersion: v1
kind: Service
metadata:
  name: authentication-linux-service
  labels:
    app: authentication-microservice
spec:
  type: LoadBalancer
  selector:
    app: authentication-microservice
  ports:
    - port: 8001
      targetPort: 8001