apiVersion: v1
kind: Service
metadata:
  name: authentication-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: authentication-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
