apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: gcr.io/portify-389116/node-app:latest
        ports:
        - containerPort: 8001
        env:
        - name: SECRET_KEY_1
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: SECRET_KEY_1
        - name: SECRET_KEY_2
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: SECRET_KEY_2
